baseURL = "https://blog.macbytes.io"
title   = "thatMacAdmin's Blog"

DefaultContentLanguage = "en"
theme = "hello-friend-ng"

pygmentsCodefences = false
pygmentsUseClasses = false

rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

# googleAnalytics = ""
# disqusShortname = ""

buildDrafts  = false
buildFuture  = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = true
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Edward Shorrock"

[blackfriday]
  hrefTargetBlank = true

# [taxonomies]
#   tag      = "tags"
#   category = ""

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Some musings on macOS, iOS, iPadOS and Apple."
  keywords = "homepage, blog, apple, mac, macOS, iOS, iPadOS, macadmins, sysadmin, macadmin"
  images = [""]

  homeSubtitle = "Some musings on macOS, iOS, iPadOS and Apple."

  # Default theme "light" or "dark"
  defaultTheme = "dark"

  gitUrl = "https://github.com/thatMacAdmin/blog.macbytes.io/commit/"

  [params.logo]
    logoText     = "$ cd ~/"
    logoHomeLink = "/"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/thatMacAdmin/"

  [[params.social]]
    name = "email"
    url  = "mailto:thatMacAdmin@macbytes.io"

  [[params.social]]
    name = "github"
    url  = "https://github.com/thatMacAdmin/"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/edshorrock/"

[languages]
  [languages.en]
    subtitle  = "Homepage & Blog"
    weight    = 1
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"
  [[menu.main]]
    identifier = "talks"
    name       = "Talks"
    url        = "talks/"
  [[menu.main]]
    identifier = "login"
    name       = "Login"
    url        = "/login"

[params.okta]
  clientId = "0oau16r2KPXjL07yp4x5"
  baseUrl = "https://dev-725200.okta.com"
  redirectUri = "https://blog.macbytes.io/login/"
